version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php_onesight
    volumes:
      - ./backend/app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    networks:
      - onesight-network

  nginx:
    image: nginx:alpine
    container_name: nginx_onesight
    volumes:
      - ./backend/app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - onesight-network

  db:
    image: mariadb:10.6
    container_name: mariadb_onesight
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: onesight
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - onesight-network

  nextjs:
    image: node:18-alpine
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - ./frontend/onesight:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - onesight-network

networks:
  onesight-network:
    driver: bridge
